import { Workspace, User, Directorate, Task, TaskComment, MeetingNote, Announcement, ActivityLog, WeeklyReport } from '../types';

export const INITIAL_WORKSPACE: Workspace = {
  id: 'ws-alpha-spark',
  name: 'Alpha Spark Workspace',
  slug: 'alpha-spark',
  ownerId: 'usr-snow',
  planTier: 'enterprise',
  createdAt: '2026-01-01T00:00:00.000Z',
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-snow',
    workspaceId: 'ws-alpha-spark',
    email: 'talk2icedmist@gmail.com',
    displayName: 'Snow (Icedmist)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    role: 'super_admin',
    directorateIds: ['dir-dev', 'dir-exec'],
    title: 'CTO & Technical Director',
  },
  {
    id: 'usr-fatima',
    workspaceId: 'ws-alpha-spark',
    email: 'fatima@alphaspark.org',
    displayName: 'Fatima Al-Hassan',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    role: 'directorate_lead',
    directorateIds: ['dir-edu'],
    title: 'Head of Teaching & Academy',
  },
  {
    id: 'usr-amina',
    workspaceId: 'ws-alpha-spark',
    email: 'amina@alphaspark.org',
    displayName: 'Amina Bello',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    role: 'directorate_lead',
    directorateIds: ['dir-dsg'],
    title: 'Lead Graphic Designer',
  },
  {
    id: 'usr-ibrahim',
    workspaceId: 'ws-alpha-spark',
    email: 'ibrahim@alphaspark.org',
    displayName: 'Ibrahim Danlami',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    role: 'directorate_lead',
    directorateIds: ['dir-fin'],
    title: 'Finance & Accounting Lead',
  },
  {
    id: 'usr-zainab',
    workspaceId: 'ws-alpha-spark',
    email: 'zainab@alphaspark.org',
    displayName: 'Zainab Abubakar',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=150&q=80',
    role: 'directorate_lead',
    directorateIds: ['dir-hr', 'dir-ops'],
    title: 'Head of HR & Operations',
  },
  {
    id: 'usr-tariq',
    workspaceId: 'ws-alpha-spark',
    email: 'tariq@alphaspark.org',
    displayName: 'Tariq Mansoor',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    role: 'member',
    directorateIds: ['dir-mkt', 'dir-prt'],
    title: 'Marketing & Partnerships Specialist',
  },
];

export const INITIAL_DIRECTORATES: Directorate[] = [
  {
    id: 'dir-dev',
    workspaceId: 'ws-alpha-spark',
    name: 'Software Engineering',
    code: 'DEV',
    description: 'Core web apps, APIs, AI integrations, and technical platform maintenance.',
    leadId: 'usr-snow',
    memberIds: ['usr-snow'],
    color: '#3B82F6', // Blue
    icon: 'Code',
  },
  {
    id: 'dir-edu',
    workspaceId: 'ws-alpha-spark',
    name: 'Teaching & Mentoring',
    code: 'EDU',
    description: 'Student instruction, course curriculum, mentorship programs, and bootcamps.',
    leadId: 'usr-fatima',
    memberIds: ['usr-fatima'],
    color: '#10B981', // Emerald
    icon: 'GraduationCap',
  },
  {
    id: 'dir-dsg',
    workspaceId: 'ws-alpha-spark',
    name: 'Graphic Design & Brand',
    code: 'DSG',
    description: 'Visual identity, marketing graphics, flyers, UI design system, media assets.',
    leadId: 'usr-amina',
    memberIds: ['usr-amina'],
    color: '#EC4899', // Pink
    icon: 'Palette',
  },
  {
    id: 'dir-mkt',
    workspaceId: 'ws-alpha-spark',
    name: 'Marketing & Growth',
    code: 'MKT',
    description: 'Social media campaigns, community management, PR, and growth analytics.',
    leadId: 'usr-tariq',
    memberIds: ['usr-tariq'],
    color: '#F59E0B', // Amber
    icon: 'Megaphone',
  },
  {
    id: 'dir-prt',
    workspaceId: 'ws-alpha-spark',
    name: 'Partnerships & NGOs',
    code: 'PRT',
    description: 'B2B relationships, university outreach, NGO alliances, and grant proposals.',
    leadId: 'usr-tariq',
    memberIds: ['usr-tariq', 'usr-snow'],
    color: '#8B5CF6', // Purple
    icon: 'Handshake',
  },
  {
    id: 'dir-fin',
    workspaceId: 'ws-alpha-spark',
    name: 'Finance & Accounting',
    code: 'FIN',
    description: 'Budgeting, payroll, invoicing, financial audits, and revenue reporting.',
    leadId: 'usr-ibrahim',
    memberIds: ['usr-ibrahim'],
    color: '#06B6D4', // Cyan
    icon: 'DollarSign',
  },
  {
    id: 'dir-hr',
    workspaceId: 'ws-alpha-spark',
    name: 'Human Resources & Recruitment',
    code: 'HR',
    description: 'Talent acquisition, onboarding, team welfare, staff performance reviews.',
    leadId: 'usr-zainab',
    memberIds: ['usr-zainab'],
    color: '#EF4444', // Red
    icon: 'Users',
  },
  {
    id: 'dir-ops',
    workspaceId: 'ws-alpha-spark',
    name: 'Operations & Procurement',
    code: 'OPS',
    description: 'Logistics, office management, hardware procurement, vendor coordination.',
    leadId: 'usr-zainab',
    memberIds: ['usr-zainab'],
    color: '#64748B', // Slate
    icon: 'Briefcase',
  },
  {
    id: 'dir-exec',
    workspaceId: 'ws-alpha-spark',
    name: 'Executive & Strategy',
    code: 'EXEC',
    description: 'Corporate strategy, quarterly goal tracking, investor updates, board governance.',
    leadId: 'usr-snow',
    memberIds: ['usr-snow', 'usr-fatima', 'usr-zainab'],
    color: '#6366F1', // Indigo
    icon: 'Shield',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-101',
    workspaceId: 'ws-alpha-spark',
    title: 'Teach Machine Learning cohort on Neural Networks',
    description: 'Prepare presentation deck and live notebook for tomorrow 4 PM session covering Backpropagation and PyTorch.',
    category: 'teaching',
    directorateId: 'dir-edu',
    assigneeIds: ['usr-fatima'],
    createdBy: 'usr-snow',
    priority: 'high',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // Tomorrow
    estimatedHours: 3,
    attachments: [
      { id: 'att-1', name: 'PyTorch_Intro_Slides.pdf', url: '#', type: 'application/pdf', size: '2.4 MB' }
    ],
    subtasks: [
      { id: 'st-1', title: 'Review student lab assignments', completed: true },
      { id: 'st-2', title: 'Set up JupyterHub environment', completed: false }
    ],
    tags: ['Machine Learning', 'Cohort 4', 'Live Session'],
    createdAt: '2026-08-07T10:00:00.000Z',
    updatedAt: '2026-08-08T09:00:00.000Z',
  },
  {
    id: 'task-102',
    workspaceId: 'ws-alpha-spark',
    title: 'Design promotional flyer for upcoming AI & Tech Webinar',
    description: 'Create high-res promotional visual for Instagram, LinkedIn, and X with custom brand colors.',
    category: 'graphic_design',
    directorateId: 'dir-dsg',
    assigneeIds: ['usr-amina'],
    createdBy: 'usr-tariq',
    priority: 'high',
    status: 'todo',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // Friday
    estimatedHours: 4,
    attachments: [],
    subtasks: [
      { id: 'st-3', title: 'Collect speaker headshots', completed: true },
      { id: 'st-4', title: 'Draft visual concept mockup', completed: false }
    ],
    tags: ['Webinar', 'Design', 'Social Media'],
    createdAt: '2026-08-08T08:30:00.000Z',
    updatedAt: '2026-08-08T08:30:00.000Z',
  },
  {
    id: 'task-103',
    workspaceId: 'ws-alpha-spark',
    title: 'Schedule student orientation for August Intake',
    description: 'Coordinate Google Meet link, send email invitations, and assign mentors to new intake.',
    category: 'student_support',
    directorateId: 'dir-edu',
    assigneeIds: ['usr-fatima', 'usr-zainab'],
    createdBy: 'usr-snow',
    priority: 'medium',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 2,
    attachments: [],
    subtasks: [
      { id: 'st-5', title: 'Draft Welcome Pack PDF', completed: true },
      { id: 'st-6', title: 'Send Calendar invites to 50 students', completed: false }
    ],
    tags: ['Orientation', 'Academy', 'Students'],
    createdAt: '2026-08-06T14:00:00.000Z',
    updatedAt: '2026-08-07T16:20:00.000Z',
  },
  {
    id: 'task-104',
    workspaceId: 'ws-alpha-spark',
    title: 'Update 2026 Alpha Spark Course Catalog & Syllabus',
    description: 'Revise curriculum details for Web Dev, Cloud Architecture, and Data Science modules.',
    category: 'custom',
    directorateId: 'dir-edu',
    assigneeIds: ['usr-fatima'],
    createdBy: 'usr-snow',
    priority: 'low',
    status: 'completed',
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 5,
    attachments: [],
    subtasks: [
      { id: 'st-7', title: 'Review module 1-4 syllabus', completed: true },
      { id: 'st-8', title: 'Publish catalog to website', completed: true }
    ],
    tags: ['Curriculum', 'Completed'],
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-07T18:00:00.000Z',
  },
  {
    id: 'task-105',
    workspaceId: 'ws-alpha-spark',
    title: 'Audit monthly Q2 operational expenditure & payroll receipts',
    description: 'Cross-reference bank statements with vendor invoices and staff stipend receipts.',
    category: 'finance',
    directorateId: 'dir-fin',
    assigneeIds: ['usr-ibrahim'],
    createdBy: 'usr-snow',
    priority: 'urgent',
    status: 'in_progress',
    dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 8,
    attachments: [],
    subtasks: [],
    tags: ['Finance', 'Audit', 'Payroll'],
    createdAt: '2026-08-05T11:00:00.000Z',
    updatedAt: '2026-08-08T07:15:00.000Z',
  },
  {
    id: 'task-106',
    workspaceId: 'ws-alpha-spark',
    title: 'Procure 10 high-performance laptops for student lab workspace',
    description: 'Request quotes from hardware vendors, submit PO to finance, and inspect delivered equipment.',
    category: 'procurement',
    directorateId: 'dir-ops',
    assigneeIds: ['usr-zainab'],
    createdBy: 'usr-snow',
    priority: 'high',
    status: 'todo',
    dueDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 6,
    attachments: [],
    subtasks: [],
    tags: ['Hardware', 'Procurement', 'Lab'],
    createdAt: '2026-08-08T09:00:00.000Z',
    updatedAt: '2026-08-08T09:00:00.000Z',
  },
  {
    id: 'task-107',
    workspaceId: 'ws-alpha-spark',
    title: 'Finalize NGO Partnership MOU for Kano Youth Innovation Hub',
    description: 'Review legal terms, define joint bootcamp obligations, and schedule signing ceremony.',
    category: 'partnership',
    directorateId: 'dir-prt',
    assigneeIds: ['usr-tariq', 'usr-snow'],
    createdBy: 'usr-snow',
    priority: 'high',
    status: 'review',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedHours: 5,
    attachments: [],
    subtasks: [],
    tags: ['Partnerships', 'NGO', 'Legal'],
    createdAt: '2026-08-04T16:00:00.000Z',
    updatedAt: '2026-08-08T11:45:00.000Z',
  },
];

export const INITIAL_COMMENTS: TaskComment[] = [
  {
    id: 'cmt-1',
    workspaceId: 'ws-alpha-spark',
    taskId: 'task-101',
    authorId: 'usr-snow',
    content: 'Hi Fatima, please make sure to include the Google Colab exercise links in the slides.',
    createdAt: '2026-08-07T12:30:00.000Z',
  },
  {
    id: 'cmt-2',
    workspaceId: 'ws-alpha-spark',
    taskId: 'task-101',
    authorId: 'usr-fatima',
    content: 'Got it! I added 3 hands-on notebooks for Neural Network training.',
    createdAt: '2026-08-07T15:10:00.000Z',
  },
];

export const INITIAL_MEETINGS: MeetingNote[] = [
  {
    id: 'mtg-1',
    workspaceId: 'ws-alpha-spark',
    title: 'Weekly Executive & Directorate Standup',
    content: 'Discussed Q3 growth targets, student onboarding timelines, and new AI workspace rollout. Key decision: Accelerate partner NGO engagement in Northern region.',
    directorateId: 'dir-exec',
    attendeeIds: ['usr-snow', 'usr-fatima', 'usr-amina', 'usr-ibrahim', 'usr-zainab'],
    date: '2026-08-07',
    actionItems: [
      { title: 'Assign Fatima to teach Machine Learning cohort tomorrow at 4 PM.', assigneeName: 'Fatima Al-Hassan' },
      { title: 'Ask Amina to design the webinar flyer by Friday.', assigneeName: 'Amina Bello' },
    ],
    createdAt: '2026-08-07T09:00:00.000Z',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    workspaceId: 'ws-alpha-spark',
    title: 'Welcome to Alpha Spark Workspace OS 🚀',
    content: 'We have launched our central operating system to manage all tasks across Engineering, Teaching, Design, HR, Finance, and Operations in one place.',
    authorId: 'usr-snow',
    targetDirectorateIds: [],
    priority: 'urgent',
    createdAt: '2026-08-08T08:00:00.000Z',
  },
];

export const INITIAL_ACTIVITY: ActivityLog[] = [
  {
    id: 'act-1',
    workspaceId: 'ws-alpha-spark',
    actorId: 'usr-snow',
    actorName: 'Snow (Icedmist)',
    action: 'created task',
    targetType: 'task',
    targetTitle: 'Teach Machine Learning cohort on Neural Networks',
    timestamp: '2026-08-07T10:00:00.000Z',
  },
  {
    id: 'act-2',
    workspaceId: 'ws-alpha-spark',
    actorId: 'usr-fatima',
    actorName: 'Fatima Al-Hassan',
    action: 'completed task',
    targetType: 'task',
    targetTitle: 'Update 2026 Alpha Spark Course Catalog & Syllabus',
    timestamp: '2026-08-07T18:00:00.000Z',
  },
];
